[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip nRF54L15"
rustflags = ["-Clink-args=-Map=/tmp/lakers-cc310.map"]

[build]
target = "thumbv8m.main-none-eabi"

[env]
DEFMT_LOG = "error"
